#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace SecMind.EditorTools
{
    // After every WebGL build, replace Unity's default cache-first ServiceWorker.js
    // with a network-first version so deploys roll out without forcing users to
    // clear their browser cache or hard-refresh.
    public sealed class WebGLPostBuildServiceWorker : IPostprocessBuildWithReport
    {
        public int callbackOrder => 0;

        public void OnPostprocessBuild(BuildReport report)
        {
            if (report.summary.platform != BuildTarget.WebGL) return;

            string buildPath = report.summary.outputPath;
            if (string.IsNullOrEmpty(buildPath) || !Directory.Exists(buildPath)) return;

            string swPath = Path.Combine(buildPath, "ServiceWorker.js");
            if (!File.Exists(swPath))
            {
                Debug.Log("[WebGLPostBuildServiceWorker] No ServiceWorker.js in build output — skipping.");
                return;
            }

            File.WriteAllText(swPath, NetworkFirstServiceWorkerSource);
            Debug.Log($"[WebGLPostBuildServiceWorker] Overwrote {swPath} with network-first strategy.");
        }

        private const string NetworkFirstServiceWorkerSource = @"// Network-first Service Worker for SecMind WebGL
// Auto-generated by WebGLPostBuildServiceWorker.cs — do not edit by hand.

const CACHE_NAME = ""Secmind-Capstone-runtime"";
const PRECACHE_URLS = [
    ""Build/docs.loader.js"",
    ""Build/docs.framework.js"",
    ""Build/docs.data"",
    ""Build/docs.wasm"",
    ""TemplateData/style.css""
];

self.addEventListener(""install"", (event) => {
    self.skipWaiting();
    event.waitUntil(
        caches.open(CACHE_NAME).then((cache) =>
            Promise.all(
                PRECACHE_URLS.map((url) =>
                    fetch(url, { cache: ""no-store"" })
                        .then((res) => (res.ok ? cache.put(url, res) : null))
                        .catch(() => null)
                )
            )
        )
    );
});

self.addEventListener(""activate"", (event) => {
    event.waitUntil(
        (async () => {
            const keys = await caches.keys();
            await Promise.all(
                keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
            );
            await self.clients.claim();
        })()
    );
});

self.addEventListener(""fetch"", (event) => {
    const req = event.request;
    if (req.method !== ""GET"") return;

    event.respondWith(
        (async () => {
            try {
                const networkResponse = await fetch(req, { cache: ""no-store"" });
                if (networkResponse && networkResponse.ok) {
                    const cache = await caches.open(CACHE_NAME);
                    cache.put(req, networkResponse.clone()).catch(() => {});
                }
                return networkResponse;
            } catch (_err) {
                const cached = await caches.match(req);
                if (cached) return cached;
                throw _err;
            }
        })()
    );
});

self.addEventListener(""message"", (event) => {
    if (event.data === ""SKIP_WAITING"") self.skipWaiting();
});
";
    }
}
#endif
